### ISSUE TITLE
\vec is not translated correctly

### ISSUE THREAD

**Issue by polarwinkel** [roniemartinez/latex2mathml#103]
The vector-arrow above a letter created with `\vec` in a formula is shown in front of the sign, not above.

When converting for example
`/vec{E}`
I get
`<mrow><mi>&#x020D1;</mi><mi>E</mi>`
as output, the expected behaviour is to get
`<mover><mi>E</mi><mo stretchy="true">&#x020D1;</mo></mover>`

**Comment by roniemartinez** [comment]
@all-contributors please add @polarwinkel  for bug
