### ISSUE TITLE
It can not convert tag  like  \begin{cases}

### ISSUE THREAD

**Issue by sinslu** [roniemartinez/latex2mathml#106]
this is  the latex   \( \begin{cases} {x=1} \\ {y=-2}\end{cases}\)

use latex2mathml convert  result is 
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mi>\(</mi><mi>\cases</mi><mrow><mrow><mrow><mi>x</mi><mo>&#x0003D;</mo><mn>1</mn></mrow></mrow><mrow><mrow><mi>y</mi><mo>&#x0003D;</mo><mo>&#x02212;</mo><mn>2</mn></mrow></mrow></mrow><mi>\)</mi></mrow></math>

it can not right  display!

**Comment by roniemartinez** [comment]
Thanks @sinslu for the bug report. I'll look into it over the weekend but you may also submit a PR just in case you are interested =)

**Comment by roniemartinez** [comment]
@all-contributors please add @sinslu for bug
