### ISSUE TITLE
`\operatorname` not recognized

### ISSUE THREAD

**Issue by abhisheksia** [roniemartinez/latex2mathml#109]
It would be great to recognize the `\operatorname` flag. It bears some similarities to `\mathrm` but they aren't entirely interchangeable. Perhaps this is a useful reference: https://github.com/osanshouo/latex2mathml/commit/18654ab803b36217a916b51546117d5e93c8fc1e

**Comment by abhisheksia** [comment]
Thank you very much! This is of great help.

**Comment by roniemartinez** [comment]
@all-contributors please add @abhisheksia for bug
