### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by StevenClontz** [roniemartinez/latex2mathml#128]
Hey, thanks for this great project. I'm adding it as a dependency to https://github.com/StevenClontz/checkit-platform to convert authors' LaTeX mathematics into MathML, which seems to be required to export question banks compatible with the Brightspace LMS.

Your conversion works pretty well, but isn't compatible with a few non-semantic commands I've been using for presentation purposes (e.g. an `\hspace{1em}` to pad out an ODE from its initial values, `\big` modifiers on parentheses because I thought it looked better in an exercise).

![image](https://user-images.githubusercontent.com/1559632/119838913-6826a880-bec9-11eb-9648-01c2da01a584.png)

I need to document my platform for a few authors who will adopt the platform this summer, which should include a style guide for mathematical notation. I think the right thing to do is to tell authors to keep their LaTeX relatively simple to make sure the MathML conversion will handle things elegantly. Does this library have any documentation on what subset of LaTeX it aims to support?

**Comment by StevenClontz** [comment]
So essentially as long as authors stick to stuff in commands.py and unimathsymbols.txt, they have a good chance at producing LaTeX that this library can handle elegantly? That's probably sufficient information.

I refactored my exercise bank to use `\qquad` already, but I'll open a separate issue about spacing.

**Comment by roniemartinez** [comment]
@all-contributors please add @StevenClontz  for bug
