### ISSUE TITLE
"\widehat, \widetilde, \fbox, \sideset" can't convert

### ISSUE THREAD

**Issue by yuwenjun1** [roniemartinez/latex2mathml#161]
like "\widehat{7+x}, \fbox{E=mc^2},  \sideset{^1_2}{^3_4}\bigotimes" are not correctly converted.

**Comment by roniemartinez** [comment]
Renamed title because `\boxed` is supported in 3.16.0 (https://github.com/roniemartinez/latex2mathml/pull/157)

**Comment by roniemartinez** [comment]
@all-contributors please add @yuwenjun1 for bug
