### ISSUE TITLE
Parsing super/subscript is different from LaTeX

### ISSUE THREAD

**Issue by amuramatsu** [roniemartinez/latex2mathml#203]
Some expressions with `^` and/or `_` are rendered different from LaTeX.

`X_12`
expected: `<mrow><msub><mi>X</mi><mn>1</mn></msub><mn>2</mn></mrow>`
actual: `<mrow><msub><mi>X</mi><mn>12</mn></msub></mrow>`

`X_\mathrm{min}`
excepted: `<mrow><msub><mi>X</mi><mrow><mo>m</mo><mo>i</mo><mo>n</mo></mrow></msub></mrow>`
actual: `<mrow><msub><mi>X</mi></msub><mrow><mi>m</mi><mi>i</mi><mi>n</mi></mrow></mrow>`

**Comment by roniemartinez** [comment]
@all-contributors please add @amuramatsu for bug
