### ISSUE TITLE
Percent signs and backslashes

### ISSUE THREAD

**Issue by StevenClontz** [roniemartinez/latex2mathml#221]
`%` begins a comment in LaTeX, so literal `%`s are denoted with `\%`. However, latex2mathml preserves the backslash in its conversion.

Given the special meaning of `\` in LaTeX, is there ever a reason to preserve it in the mathml conversion? I believe it'd only be displayed in LaTeX when using something like `\setminus` or `\backslash`.

**Comment by roniemartinez** [comment]
@StevenClontz can you provide an example? Converting `\%` seems to produce the correct output.

```bash
% l2m -b -t '\%'

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>&#x00025;</mi></mrow></math>
```

**Comment by StevenClontz** [comment]
Run in a Python 3 kernel in a Jupyter notebook:

![image](https://user-images.githubusercontent.com/1559632/125136225-082e3f00-e0d0-11eb-8225-f0dd7fc1b938.png)

```
tex = r"99\%"
from latex2mathml.converter import convert
convert(tex)
```

returns:

```
'<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mrow><mn>99</mn><mi>\\</mi><mi>%</mi></mrow></math>'
```

I tried on the commandline: `\%` behaves as expected, but `99\%` does not. (Note that my version is stale; apologies for not upgrading first.)

```
user@project-0b735a53-2e2b-4036-8489-d78a5a2e237c ~ 
$ python -m pip show latex2mathml
Name: latex2mathml
Version: 3.0.0
Summary: Pure Python library for LaTeX to MathML conversion
Home-page: https://github.com/roniemartinez/latex2mathml
Author: Ronie Martinez
Author-email: ronmarti18@gmail.com
License: MIT
Location: /home/user/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
user@project-0b735a53-2e2b-4036-8489-d78a5a2e237c ~ 
$ l2m -b -t '\%'
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>&#x00025;</mi></mrow></math>
user@project-0b735a53-2e2b-4036-8489-d78a5a2e237c ~ 
$ l2m -b -t '99\%'
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mn>99</mn><mi>\</mi><mi>%</mi></mrow></math>
```

**Comment by roniemartinez** [comment]
@StevenClontz Can you try the latest version? I remember I rewrote the parser.

```bash
% l2m -V
latex2mathml 3.61.0
% l2m -b -t '99\%'
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mn>99</mn><mi>&#x00025;</mi></mrow></math>
```

**Comment by StevenClontz** [comment]
Sorry for the trouble, upgrading to 3.61 fixes this issue. Thanks for your help!
