### ISSUE TITLE
bad presentation of \sum

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#288]
when the result of 
```
s = r"\sum_{i=1}^{10}\frac{ \large \sigma_{zp,i}}{E_i} kN"

convert_to_mathml(s)
```
is copied into MS Word, we can find that there is an extra dotted-line block after the `\sum` symbol

is it a bug?

![mathml](https://user-images.githubusercontent.com/7960913/161058200-c875ef30-5c41-4251-bfeb-3ee67fe02611.png)

**Comment by retsyo** [comment]
my bad, it should be
```
r"\sum_{i=1}^{10}{\frac{\sigma_{zp,i}}{E_i} kN"
```

**Comment by retsyo** [comment]
sorry to re-open
should `\sum_{i=1}^{10}\frac{\sigma_{zp,i}} {E_i} kN` mean
![mathml](https://user-images.githubusercontent.com/7960913/161229190-a15da955-86da-4c17-840d-0d3b31300e28.png)

now it is
![mathml](https://user-images.githubusercontent.com/7960913/161229271-2777cf22-1e11-4a5f-abb2-5008ea6847b6.png)

**Comment by retsyo** [comment]
the same thing happens on
```
\int_{1}^{5}x\mathrm{d}x
\prod_{j=1}^{3} y_{j}
\lim\limits_{x \to 0} \frac{a^x}{b+c}

```

**Comment by roniemartinez** [comment]
Closing this for now as I cannot see any difference between latex2mathml output and MathJax.

> the same thing happens on

I wrote a separate ticket in https://github.com/roniemartinez/latex2mathml/issues/301

![image](https://user-images.githubusercontent.com/2573537/162025944-46f8ed89-3dbf-45ba-8b5b-61b75f5c303a.png)

**Comment by retsyo** [comment]
the problem can be solved easily: use `{}` to embrace every item, for example, we do not use 
```
\int_{1}^{5}x\mathrm{d}x   

\prod_{j=1}^{3} y_{j}   

\lim\limits_{x \to 0} \frac{a^x}{b+c}  
```
but use
```
\int_{1}^{5}{x}\mathrm{d}x
\prod_{j=1}^{3} {y_{j}}
\lim\limits_{x \to 0} {\frac{a^x}{b+c}}
```
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/162552686-ada23652-8ab5-45b2-8edc-87fd280a9f0c.png)
