### ISSUE TITLE
maybe improvement on distance between hat and single letter

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#290]
`\bar{H}` creates a hat on `H`, the distance between `\bar` and `H` is ok
![mathml](https://user-images.githubusercontent.com/7960913/161239811-fc1440c8-2c61-4eeb-97dd-eac1d6efde5c.png)

however, for other kind of `hat`, i.e.
```
\hat{H} \quad \grave{H} \quad \check{H} \quad \vec{H} \quad \tilde{H} \quad \dot{H} \ quad \ddot{H} \quad \dddot{H} \quad \ddddot{H} \quad \widehat{H}
```
the distance between `hat` and `H` are too big. Is it a feature of MathML? Or we can adjust the distance?
![mathml](https://user-images.githubusercontent.com/7960913/161240656-ad7ba34b-c9c8-45cc-9301-a8c34fd1f612.png)

the same code is rendered on https://www.codecogs.com/latex/eqneditor.php which is expected
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161241071-15bfe434-04ed-4b16-be51-49746867e390.png)

**Comment by roniemartinez** [comment]
The rendered output in MathJax viewer is quite OK.

![image](https://user-images.githubusercontent.com/2573537/162027156-a8256f62-927d-4c6f-8a3f-af039a51979e.png)
