### ISSUE TITLE
\left \right do not make big parenthesis

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#292]
`\sin \left (x + \frac {\pi} {2}\right)` should makes big `(` and `)`, however this package does not
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161259974-ca856e8c-c11e-4c8c-930f-177dccf3457c.png)

this is https://www.codecogs.com/latex/eqneditor.php does
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161260070-38ad4953-6db0-487b-bda9-02e92ccb13a7.png)

**Comment by roniemartinez** [comment]
The latex2mathml output is properly rendered in MathJax viewer. It's probably that DOCX does not support "stretchy" attribute.

![image](https://user-images.githubusercontent.com/2573537/162027855-41035b34-29e2-4e10-8e4f-a9bfec7cd1a9.png)
