### ISSUE TITLE
\overline and \underline is not corrected

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#294]
latex2mathml renders 
```
\overline{x+y} \qquad \underline{a+b}
```
as 
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161261121-b0f169e7-48ea-46db-831c-072ad1714be9.png)

but it should be 
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161261220-fc077bb8-5eaf-497e-8d89-a8816a99b425.png)

**Comment by retsyo** [comment]
\overbrace and \underbrace are same

![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161262206-d22c69e0-1168-4982-8944-01732c8c70f3.png)

![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161262242-9ba96ad0-512d-4413-b380-9638ccf6e919.png)

**Comment by roniemartinez** [comment]
Can you add the Latex for \overbrace and \underbrace so I can test?

**Comment by retsyo** [comment]
`\overbrace{1+2+\cdots+n}^{there are n}` 

and
` \underbrace{a+b+\cdots+z}_{26}`

**Comment by roniemartinez** [comment]
latex2mathml output is correctly rendered in MathJax viewer. I created a separate ticket for `\overbrace and \underbrace` in https://github.com/roniemartinez/latex2mathml/issues/302

![image](https://user-images.githubusercontent.com/2573537/162029388-e648cf38-338a-4c8d-9440-3083377ba021.png)
