### ISSUE TITLE
\overrightarrow and \overleftarrow is wrong

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#295]
`\overrightarrow{ABC} + \overleftarrow{DEF}`
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161262590-0b22eae3-8a1b-40f9-b450-5b7355e47266.png)

but it should be 
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161262724-eb6ada75-3eba-4c71-b032-bc387ba4a651.png)

**Comment by roniemartinez** [comment]
latex2mathml output is rendered properly in MathJax viewer. DOCX probably does not support it.

![image](https://user-images.githubusercontent.com/2573537/162028112-953c0aad-c1a3-4a20-9a48-577059c9b475.png)
