### ISSUE TITLE
bmatrix/Bmatrix/vmatrix/Vmatrix/cases render short symbol

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#296]
```
\begin{bmatrix}  1 & 2 & \cdots \\  67 & 95 & \cdots \\  \vdots & \vdots & \ddots \\ \end{bmatrix}
```
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161263205-2ecc7370-5ded-4fc8-bc41-731eb64f4ca6.png)

but it should be 
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161263277-05f4de04-723b-417d-ba33-f979b4e1b5b3.png)

**Comment by retsyo** [comment]
`\begin{vmatrix} 1 &  2&  3 \\ 4 &  5&  6\\ \end{vmatrix}` is bad too
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161265144-e3505bc0-3428-41b9-840a-be7aae9465c6.png)

**Comment by retsyo** [comment]
`\begin{Bmatrix} 1 &  2\\ 3 &  4\\ 5 &  5\\ \end{Bmatrix}`

`\begin{Vmatrix} 1 & 2 &  3\\ 4 & 5 & 6 \\ 7 & 8 & 9 \\ \end{Vmatrix}`

`\left\{\begin{matrix} 1 &  2\\ 4 &  5\\ 6 &  7\\ \end{matrix}\right.`

`\left.\begin{matrix} 1 &  2\\ 3 &  4\\ 5 &  6\\ \end{matrix}\right|`

all have short symbol

**Comment by roniemartinez** [comment]
It looks like all the rendering issue here like short brackets and spaces on accents are a problem with MS Word because all the outputs are working properly with Mathjax which is always my source of truth. I always try to compare the one generated by latex2mathml.

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/2573537/161282892-844ddf9b-eb9d-4a58-8054-3c9995e989cb.png">

@retsyo can you also verify? I am both using Mathjax and Katex as reference for correct output. MS Word probably does not support these.

**Comment by retsyo** [comment]
then could you please give some suggestion on writing kinds of matrix in DOCX?

since I and some other users(like stated on https://github.com/python-openxml/python-docx/issues/320) use latex2mathml to write equation in DOCX.

**Comment by roniemartinez** [comment]
@retsyo 
Would it be an option to add SVG or PNG to docx files instead of raw MathML? There is a library that uses `latex2mathml` output and convert them to SVG/PNG called [ziamath](https://ziamath.readthedocs.io/en/latest/).

I would also try to take a look and find more options.

**Comment by retsyo** [comment]
Thanks, to insert a pic is valid for DOCX, this is what I did if there is only few equation before. Then I found the metioned https://github.com/python-openxml/python-docx/issues/320 which try to convert latex equation string and insert as Ms Word equation 

I tested https://ziamath.readthedocs.io/en/latest/, and found that
1. https://ziamath.readthedocs.io/en/latest/ does not support some features missing in latex2mathml too, for example, `\xleftarrow[abc]{hello}`, `\overbrace{1+2+\cdots+n}^{there   are n} \qquad \underbrace{a+b+\cdots+z}_{26}`, `\left.\begin{matrix} 1 &  2\\ 3 &  4\\ 5 &  6\\ \end{matrix}\right|`

2. on my windows 10 64 bits, I can't make cairosvg runs on python 3.8, but it runs on python 3.6; however, https://ziamath.readthedocs.io/en/latest/ runs on python 3.8, but does not runs on python 3.6. So I use 2 versions of python to convert latex string to equation image

btw, to use a real equation could be still a better solution which has been requested many times on https://github.com/python-openxml/python-docx

**Comment by roniemartinez** [comment]
> Did you try the stylesheet used in the link?

It looks like you did in https://github.com/roniemartinez/latex2mathml/issues/287#issuecomment-1085438838. I am not really sure of other solution other than using ziamath.

As for cairosvg, they have `Python 3.6+` stated on their README. Maybe you can open a ticket in their project repo: https://github.com/Kozea/CairoSVG

**Comment by roniemartinez** [comment]
Closing this issue. Please read my comment in https://github.com/roniemartinez/latex2mathml/issues/287#issuecomment-1093470723
