### ISSUE TITLE
{split} is treatas invalid

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#297]
```
\begin{split}  \cos 2x &= \cos^2x - \sin^2x \\  &=2\cos^2x-1  \end{split}
```
should be 
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/161264099-72e65502-2675-41d0-81d8-fa85036e7de1.png)

**Comment by roniemartinez** [comment]
Not implemented yet, so I am treating this as feature request

**Comment by sinslu** [comment]
> Not implemented yet, so I am treating this as feature request

hi, this type  \begin{xxxx}  like \begin{align}  also not implemented yet!
