### ISSUE TITLE
shoud \frac \dfrac \cfrac be in different size?

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#298]
it seems that latex2mathml render `\frac 1 2`, `\dfrac 1 2`  and  `\cfrac 1 2` in same size

**Comment by roniemartinez** [comment]
latex2mathml output is similar to MathJax. Probably DOCX does not support this.

![image](https://user-images.githubusercontent.com/2573537/162028531-6edd0a26-9ab9-4c91-b2cf-9cf48c806cb7.png)
