### ISSUE TITLE
\not mis-places the line

### ISSUE THREAD

**Issue by retsyo** [roniemartinez/latex2mathml#313]
```
\not \in \qquad,\qquad \not \ni \qquad,\qquad \not a \qquad,\qquad \not\equiv \qquad,\qquad \not\operatorname{R}
```
should displays as 
![latex](https://user-images.githubusercontent.com/7960913/162579393-613b95e8-e82f-4566-a136-74d5fee5de64.png)

but now in DOCX, it is shown as 
![CodeCogsEqn](https://user-images.githubusercontent.com/7960913/162579430-fce4fc19-8b2b-4075-a9d9-d3bd7930bed4.png)
in other words, the `/` is not over-drawn on the latter character

**Comment by retsyo** [comment]
no, the generated mathml string does not place `/` on characters no matter in https://www.tutorialspoint.com/online_mathml_editor.php or DOCX
![mathml](https://user-images.githubusercontent.com/7960913/162597286-67072231-824a-4e64-b84a-e7d174a88a66.png)

**Comment by roniemartinez** [comment]
Did you update your version?

The output for `\not \in` is `&#x02209;` which is the unicode for `∉` which is equivalent to `\nin`.

**Comment by retsyo** [comment]
yes, I am using latest cloned version

**Comment by roniemartinez** [comment]
The way to verify that you are running the correct version is when `\not \in` and `\nin` have the same output.

```console
$ l2m -b -t '\not \in'                                                                                                     
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>&#x02209;</mi></mrow></math>
```

```console
$  l2m -b -t '\nin'    
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mo>&#x02209;</mo></mrow></math>
```

You can use the MathJax viewer from their official website: https://www.mathjax.org/#demo
