### ISSUE TITLE
[Feature Request] Missing ensemble set

### ISSUE THREAD

**Issue by DenisSalem** [roniemartinez/latex2mathml#51]
Hello there, I'm using 2.6.7 version.

I would report the fact that _ensembles set_ are missing. 
https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols#Set_and.2For_logic_notation

As an exemple, it could be nice to have both \R and \mathbb{R} giving ℝ.

**Comment by roniemartinez** [comment]
Thanks. Will review this.

**Comment by roniemartinez** [comment]
Hi @DenisSalem 

I added support for Math alphabets (`\mathbb{}`, etc). However, symbols like `\R`, `\N` and similar will not be supported for now as I cannot find them on the list (unimathsymbols.txt) compiled by Günter Milde.
