### ISSUE TITLE
\bar doesn't work as expected

### ISSUE THREAD

**Issue by DenisSalem** [roniemartinez/latex2mathml#52]
Hello there, I'm using the version 2.6.7

I try to use \bar to write _complex number_ related equation.

> \bar{z_1} = z_2

should produce something like

```
<math>
<mrow>
    <mover accent="true">
        <mrow>
            <msub>
                <mi>z</mi>
                <mn>1</mn>
            </msub>
        </mrow>
        <mo>&macr;</mo>
    </mover>
    <mo>=</mo>
    <msub>
        <mi>z</mi>
        <mn>2</mn>
    </msub>
</mrow>
</math>
```

instead I got

 ```
<math>
    <mrow>
        <mi>&#x00304;</mi>
        <mrow>
             <msub>
                 <mi>z</mi>
                 <mn>1</mn>
             </msub>
        </mrow>
        <mo>&#x0003D;</mo>
        <msub>
            <mi>z</mi>
            <mn>2</mn>
        </msub>
    </mrow>
</math>
```
Is there something I'm doing wrong?

**Comment by roniemartinez** [comment]
Hi @DenisSalem 

The \bar is not implemented yet. It only uses the \bar inside the unimathsymbols.txt. I will look into it.

**Comment by DenisSalem** [comment]
Thank you :)

**Comment by roniemartinez** [comment]
@DenisSalem I will be delaying this for a bit (and other issues) as I will be very busy for the next 2 weeks. I will be teaching high school and college students. Thanks!

**Comment by DenisSalem** [comment]
![](http://www.reactiongifs.com/r/me3.gif "")
