### ISSUE TITLE
gaint error

### ISSUE THREAD

**Issue by aspnetcs** [roniemartinez/latex2mathml#53]
>>> latex_input = '\frac{1}{2}'
>>> mathml_output = latex2mathml.converter.convert(latex_input)
>>> mathml_output
'<math><mrow><mi>r</mi><mi>a</mi><mi>c</mi><mrow><mn>1</mn></mrow><mrow><mn>2</mn></mrow></mrow></math>'

**Comment by roniemartinez** [comment]
It is working, you are escaping `f` with the backslash.

use `r'\frac{1}{2}'` or `'\\frac{1}{2}'`
