### ISSUE TITLE
Incorrect conversion with xmlns="w3.org"

### ISSUE THREAD

**Issue by cassiusoat** [roniemartinez/latex2mathml#55]
Hello there, I want to know whether latex2mathml supports `<math xmlns="http://www.w3.org/1998/Math/MathML">`

for example, when converting `\begin{array}{rcl}ABC&=&a\\A&=&abc\end{array}` to mathml
the latex2mathml obtains the incorrect conversion
[latex2mathml_result.txt](https://github.com/roniemartinez/latex2mathml/files/3319507/latex2mathml_result.txt)

but the web  application in [www.wiris.com](http://www.wiris.com/editor/demo/en/developers#mathml-latex) could get the correct result.
[wiris_result.txt](https://github.com/roniemartinez/latex2mathml/files/3319500/wiris_result.txt)

**Could latex2mathml obtain the same result from [www.wiris.com](http://www.wiris.com/editor/demo/en/developers#mathml-latex)?**

**Comment by roniemartinez** [comment]
Hi @cassiusoat,

You might have swapped the outputs on the text files :). LaTex2MathML output is definitely not right.

Please give me time to fix this as I have a hectic schedule. Also, this is open for Pull Requests.

Thank you for spotting it!

**Comment by roniemartinez** [comment]
Related to #57
