### ISSUE TITLE
'[]' not correct

### ISSUE THREAD

**Issue by Sun-ZhenXing** [roniemartinez/latex2mathml#77]
r"\left[\begin{matrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\0 & 0 & 1 & 0\\0 & 0 & 0 & 1\end{matrix}\right]"
It looks like this: ![image](https://user-images.githubusercontent.com/44517244/79064479-fe0a6e80-7cdb-11ea-846f-046991dd4191.png), not this:
![image](https://user-images.githubusercontent.com/44517244/79064515-0c588a80-7cdc-11ea-946c-832ca3861942.png)

PS: Edit: '$' is not included.

**Comment by roniemartinez** [comment]
@Sun-ZhenXing 

I found issues here while testing:
1. Your latex string are missing "\\" in-between matrix rows. 
2. Even MathJax cannot render it correctly. (see image below)
   ![image](https://user-images.githubusercontent.com/2573537/79573890-e4a95e00-80f1-11ea-81d2-66214b45ff45.png)
3. The correct string should be `r"\left[\begin{matrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\0 & 0 & 1 & 0\\0 & 0 & 0 & 1\end{matrix}\right]"`
4. `latex2mathml` can correctly generate the corresponding MathML as seen below:
```mathml
<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mrow><mo fence="true" form="prefix" stretchy="true">[</mo><mrow><mtable><mtr><mtd><mn>1</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd></mtr><mtr><mtd><mn>0</mn></mtd><mtd><mn>1</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd></mtr><mtr><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>1</mn></mtd><mtd><mn>0</mn></mtd></mtr><mtr><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>1</mn></mtd></mtr></mtable></mrow><mo fence="true" form="postfix" stretchy="true">]</mo></mrow></mrow></math>
```

### Rendering
Trying to view it on MathJax viewer correctly renders it:
![image](https://user-images.githubusercontent.com/2573537/79574232-6bf6d180-80f2-11ea-8591-d9bfda89caf3.png)

It is possible that you are missing the right styling for these:
1. `<mo fence="true" form="prefix" stretchy="true">[</mo>`
2. `<mo fence="true" form="postfix" stretchy="true">]</mo>`

**Comment by Sun-ZhenXing** [comment]
Thank you for your help.
But, the string is this r"\left[\begin{matrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\0 & 0 & 1 & 0\\0 & 0 & 0 & 1\end{matrix}\right]", and this was created by SymPy. When I type it into textbox, it was somehow converted to \\. And the string which I tested is r"\left[\begin{matrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\0 & 0 & 1 & 0\\0 & 0 & 0 & 1\end{matrix}\right]".
The problem is I need a big "[", not just a "[". 
Then I find the problem is Word, not latex2mathml or SymPy.
