### ISSUE TITLE
Trigonometric functions ?

### ISSUE THREAD

**Issue by oliverstefanov** [roniemartinez/latex2mathml#90]
I always get a backward slash when converting trigonometric function, for example "\cos" converts to "\cos".

Is this the expected behavior ? Are trigonometric functions not implemented ?

If not I suppose I can write a routine to clean this up

**Comment by roniemartinez** [comment]
@oliverstefanov I have not implemented trigonometric functions yet and a lot more, actually. Feel free to make pull requests.

**Comment by oliverstefanov** [comment]
Alright thanks!

**Comment by roniemartinez** [comment]
@all-contributors please add @oliverstefanov for bug
