### ISSUE TITLE
Something wrong about the '\mathrm{}'

### ISSUE THREAD

**Issue by cesaryuan** [roniemartinez/latex2mathml#94]
Why must there be a space between the '\mathrm' and '{}'. 
I test it that '\mathrm {}' can be converted correctly but not the '\mathrm{}'.
 
![image](https://user-images.githubusercontent.com/35998162/85247760-66669080-b481-11ea-91a2-cb8636e5e36c.png)

l2m version: 2.14.0
Python version: 3.7.6
Operating System: Windows 10

**Comment by roniemartinez** [comment]
@all-contributors please add @cesaryuan for bug
